#!/bin/bash

# deps: bash, coreutils, apt, dialog, grep, sudo
# + aptitude, nala (optional)
# Last update 2025/12/16 by pavroo

DIALOG="`which dialog`"
YESNO="--yesno "
HEIGHT="20"
WIDTH="80"
MENUHEIGHT="12"
TITLE="--title "
ENTRY="--inputbox "
MENU="--menu"
TEXT=""
TITLETEXT="Sparky Kernel Tool"

MANAGER=`cat /tmp/sparky-mgr`
if [ "$MANAGER" = "APT" ]; then
	MANAGER="apt"
elif [ "$MANAGER" = "Aptitude" ]; then
	MANAGER="aptitude"
elif [ "$MANAGER" = "Nala" ]; then
	MANAGER="nala"
else
	MANAGER="apt"
fi

if [ -f /tmp/sparky-kernel ]; then
	sudo rm -f /tmp/sparky-kernel
fi
if [ -f /tmp/sparky-kernel ]; then
	clear
	echo ""
	echo "  sparky-kernel file is locked!"
	echo "  clean it up before launching it again!"
	echo ""
	sudo rm -f /tmp/sparky-kernel
fi

clear
$DIALOG $TITLE"$TITLETEXT" $MENU $TEXT"\nChoose an action using $MANAGER :" $HEIGHT $WIDTH $MENUHEIGHT \
Back "Back to main menu" \
Debian "Install Debian Linux kernel" \
Liquorix "Install Liquorix Linux kernel" \
Sparky "Install Sparky Linux kernel" \
XanMod "Install XanMod Linux kernel" \
Remove "Uninstall a Linux kernel" \
Exit "Exit" 2>/tmp/sparky-kernel

if [ "$?" = "0" ]; then
	ACTIONKER=`cat /tmp/sparky-kernel`
else
	clear
	exit 0
fi

clear

if [ "$ACTIONKER" = "Back" ]; then
	clear
	spt
elif [ "$ACTIONKER" = "Debian" ]; then
	clear
	sudo /usr/lib/sparky-package-tool/debian-kernel
elif [ "$ACTIONKER" = "Liquorix" ]; then
	clear
	sudo /usr/lib/sparky-package-tool/liquorix-kernel
elif [ "$ACTIONKER" = "Sparky" ]; then
	clear
	sudo /usr/lib/sparky-package-tool/sparky-kernel
elif [ "$ACTIONKER" = "XanMod" ]; then
	clear
	sudo /usr/lib/sparky-package-tool/xanmod-kernel
elif [ "$ACTIONKER" = "Remove" ]; then
	clear
	sudo /usr/lib/sparky-package-tool/old-kernel
elif [ "$ACTIONKER" = "Exit" ]; then
	clear
	exit 0
else
	clear
	exit 0	
fi

exit 0
